apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cnp-ftp-rule"
  namespace: default        #change default namespace to match your namespace
spec:
  description: "This policy will block the outbound FTP connections"
  endpointSelector:
    matchLabels: 
      app: file-pod # Change your matchLabels
  egress:
    - toPorts:
        - ports:
            - port: "20"
              protocol: TCP
            - port: "21"
              protocol: TCP
            - port: "990"
              protocol: TCP
            - port: "69"
              protocol: UDP
