apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cnp-egress-t1071-ftp-rule"
  namespace: default        #change default namespace to match your namespace
spec:
  description: "Policy to Deny FTP Outgoing Traffic"
  endpointSelector:
    matchLabels:
      app: test           #change app: test to match your label
  egress:
    - toPorts:
        - ports:
            - port: "20"
              protocol: TCP
            - port: "21"
              protocol: TCP
            - port: "990"
              protocol: TCP
            - port: "69"
              protocol: UDP
