apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnp-mitre-t1571-mysql-ingress
spec:
  description: "Allow standard ports of MySQL pods"
  endpointSelector:
    matchLabels:
      app: mysql              # Change label with your own labels
  ingress:
  - toPorts:
    - ports:
      - port: "3306"
        protocol: TCP
      - port: "33060"
        protocol: TCP
