apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cnp-ftp-rule"
spec:
  description: "This policy will block the inbound FTP connection"
  endpointSelector:
    matchLabels:
      app: ftp-pod
  ingress:
    - toPorts:
        - ports:
            - port: "20"
              protocol: TCP
            - port: "21"
              protocol: TCP
            - port: "990"
              protocol: TCP
            - port: "69"
              protocol: UDP
