# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-postgresql-config-directory
  namespace: default  #change with your namespace
spec:
  tags: ["PostgreSQL", "MITRE"]
  message: "PostgreSQL files accessed by unknown process"
  selector:
    matchLabels:
      app: testpod #change with your match label
  file:
    matchDirectories:
      - dir: /etc/postgresql/
        recursive: true
        readOnly: false
      - dir: /etc/postgresql-common/
        recursive: true
        readOnly: false
    action: Audit
    severity: 5
