# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-non-application-layer-protocol
  namespace: default # Change your namespace
spec:
  tags: ["MITRE", "system", "ksp", "T1016"]
  message: “Alert! audited the non-application layer protocol communication”
  selector:
    matchLabels:
      pod: ubuntu      #change the labels 
  process:
    severity: 5       # medium severity
    matchPaths:
    - path: /bin/ping 
    action: Audit
