# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-allow-elastic-access-file-config-index
  namespace: default        #change namespace to match your namespace
spec:
  tags: ["Elastic", "Allow Policy", "Baseline policy"]
  message: "config or index files accessed by Elastic Binary"
  severity: 1
  selector:
    matchLabels:
      app: elastic     #change label to match your label
  file:
   matchDirectories:
    - dir: /usr/share/elasticsearch/config/
      fromSource:
      - path: /usr/share/elasticsearch/jdk/bin/java
    - dir: /usr/share/elasticsearch/data/nodes/0/indices/OzKpS1ecQDGQWEoOwxbOkA/0/index/
      fromSource:
      - path: /usr/share/elasticsearch/jdk/bin/java
  action: Allow
