# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name:ksp-allow-elastic-access-process-ldconfig-java-bincontroller
  namespace: default        #change namespace to match your namespace
spec:
  tags: ["Elastic", "Allow Policy", "Baseline-policy", "JAVA"]
  message: "java or config process accessed by Elastic Binary"
  severity: 1
  selector:
    matchLabels:
      app: elastic     #change label to match your label

  process:
    matchPaths:
    - path: /sbin/ldconfig
      fromSource:
      - path: /usr/share/elasticsearch/jdk/bin/java
    - path: /usr/share/elasticsearch/jdk/bin/java
      fromSource:
      - path: /usr/bin/bash
    - path: /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
      fromSource:
      - path: /usr/share/elasticsearch/jdk/bin/java
  action: Allow
