apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "ingress elastic search allow only port 9200"
spec:
  endpointSelector:
    matchLabels:
      {}		
  ingress:
  - fromCIDR:
      {}
    toPorts:
    - ports:
      - port: "9200"
        protocol: TCP
